abstract final class IlaiosSurfaceCatalog {
  static const Map<String, String> _en = <String, String>{
    'deliveries.title': 'Deliveries',
    'deliveries.note': 'Only artifacts present in the verified evidence chain are offered here. Saving is an explicit user action; Desktop retrieves bytes from the authoritative evidence store and never fabricates a finished product.',
    'deliveries.empty': 'No verified deliverable artifacts are available yet.',
    'deliveries.savedPrefix': 'Saved verified artifact to',
    'deliveries.execution': 'Execution',
    'deliveries.saving': 'Saving…',
    'deliveries.save': 'Save',
    'live.title': 'Live Execution',
    'live.footer': 'Displayed values are read-only projections of authenticated backend state. Desktop does not schedule or execute work from this surface.',
    'live.runtimeRoutes': 'Runtime routes',
    'live.liveEvents': 'Live events',
    'live.activeLeases': 'Active leases',
    'live.recordedEffects': 'Recorded effects',
    'live.lastEvent': 'Last live event',
    'live.controlPlane': 'Control plane',
    'evidence.title': 'Evidence & Audit',
    'evidence.footer': 'The backend verifies the provenance chain before these records are returned. Desktop displays metadata only; artifact bytes, base64 payloads and secret material are not requested or rendered.',
    'evidence.verifiedRecords': 'Verified records',
    'evidence.displayedRecords': 'Displayed records',
    'evidence.verification': 'Verification',
    'evidence.verified': 'Verified',
    'evidence.unavailable': 'Unavailable',
    'evidence.empty': 'No verified evidence records available.',
    'evidence.execution': 'Execution',
    'evidence.chain': 'chain',
    'governance.title': 'Governance',
    'governance.footer': 'Approval controls are rendered only for backend-admitted work whose persisted policy requires human approval. Desktop cannot change risk class, execute work directly, bypass admission, or expose secret references.',
    'governance.registeredGrants': 'Registered grants',
    'governance.revokedGrants': 'Revoked grants',
    'governance.stoppedSubjects': 'Stopped subjects',
    'governance.pendingApprovals': 'Pending approvals',
    'governance.empty': 'No pending governed work.',
    'governance.noApprover': 'Independent approver identity is not configured. Decisions are disabled.',
    'governance.malformed': 'Malformed request',
    'governance.requester': 'Requester',
    'governance.requesterUnavailable': 'Requester unavailable',
    'governance.independentRequired': 'Independent approver required',
    'governance.deny': 'Deny',
    'governance.approve': 'Approve',
  };

  static const Map<String, String> _tr = <String, String>{
    'deliveries.title': 'Teslimatlar',
    'deliveries.note': 'Burada yalnızca doğrulanmış kanıt zincirinde bulunan çıktılar sunulur. Kaydetme açık bir kullanıcı işlemidir; Desktop baytları yetkili kanıt deposundan alır ve bitmiş ürün uydurmaz.',
    'deliveries.empty': 'Henüz doğrulanmış teslim edilebilir çıktı yok.',
    'deliveries.savedPrefix': 'Doğrulanmış çıktı şuraya kaydedildi:',
    'deliveries.execution': 'Yürütme',
    'deliveries.saving': 'Kaydediliyor…',
    'deliveries.save': 'Kaydet',
    'live.title': 'Canlı Yürütme',
    'live.footer': 'Gösterilen değerler, kimliği doğrulanmış arka uç durumunun salt okunur projeksiyonlarıdır. Desktop bu ekrandan iş planlamaz veya yürütmez.',
    'live.runtimeRoutes': 'Çalışma zamanı rotaları',
    'live.liveEvents': 'Canlı olaylar',
    'live.activeLeases': 'Aktif kiralamalar',
    'live.recordedEffects': 'Kaydedilmiş etkiler',
    'live.lastEvent': 'Son canlı olay',
    'live.controlPlane': 'Kontrol düzlemi',
    'evidence.title': 'Kanıt ve Denetim',
    'evidence.footer': 'Arka uç, kayıtlar döndürülmeden önce kaynak/provenance zincirini doğrular. Desktop yalnızca metadata gösterir; çıktı baytları, base64 yükleri ve gizli materyal istenmez veya görüntülenmez.',
    'evidence.verifiedRecords': 'Doğrulanmış kayıtlar',
    'evidence.displayedRecords': 'Gösterilen kayıtlar',
    'evidence.verification': 'Doğrulama',
    'evidence.verified': 'Doğrulandı',
    'evidence.unavailable': 'Kullanılamıyor',
    'evidence.empty': 'Doğrulanmış kanıt kaydı bulunmuyor.',
    'evidence.execution': 'Yürütme',
    'evidence.chain': 'zincir',
    'governance.title': 'Yönetişim',
    'governance.footer': 'Onay kontrolleri yalnızca kalıcı politikası insan onayı gerektiren ve arka uç tarafından kabul edilmiş işler için gösterilir. Desktop risk sınıfını değiştiremez, işi doğrudan yürütemez, kabul denetimini atlayamaz veya gizli referansları açığa çıkaramaz.',
    'governance.registeredGrants': 'Kayıtlı yetkiler',
    'governance.revokedGrants': 'İptal edilen yetkiler',
    'governance.stoppedSubjects': 'Durdurulan özneler',
    'governance.pendingApprovals': 'Bekleyen onaylar',
    'governance.empty': 'Bekleyen yönetilen iş yok.',
    'governance.noApprover': 'Bağımsız onaylayıcı kimliği yapılandırılmamış. Kararlar devre dışı.',
    'governance.malformed': 'Hatalı istek',
    'governance.requester': 'İstek sahibi',
    'governance.requesterUnavailable': 'İstek sahibi kullanılamıyor',
    'governance.independentRequired': 'Bağımsız onaylayıcı gerekli',
    'governance.deny': 'Reddet',
    'governance.approve': 'Onayla',
  };

  static String? text(String localeCode, String key) {
    final catalog = localeCode == 'tr' ? _tr : _en;
    return catalog[key] ?? _en[key];
  }
}
