abstract final class IlaiosHomeCatalog {
  static const Map<String, String> _tr = <String, String>{
    'Active Workflow': 'Aktif İş Akışı',
    'Started': 'Başlangıç',
    'Runtime unavailable': 'Çalışma zamanı kullanılamıyor',
    'Refresh authoritative state': 'Yetkili durumu yenile',
    'Goal Intake': 'Hedef Alımı',
    'Intent accepted': 'İstek kabul edildi',
    'Planning': 'Planlama',
    'Workflow prepared': 'İş akışı hazırlandı',
    'Execution': 'Yürütme',
    'Agents executing': 'Ajanlar yürütüyor',
    'Verification': 'Doğrulama',
    'Tests & evidence': 'Testler ve kanıt',
    'Delivery': 'Teslimat',
    'Finished product': 'Bitmiş ürün',
    'Overall Progress': 'Genel İlerleme',
    'LIVE EXECUTION': 'CANLI YÜRÜTME',
    'active': 'aktif',
    'No active worker leases are exposed by the scheduler.': 'Zamanlayıcı tarafından gösterilen aktif çalışan kiralaması yok.',
    'LIVE WORKSPACE': 'CANLI ÇALIŞMA ALANI',
    'Live Code': 'Canlı Kod',
    'Terminal': 'Terminal',
    'Browser': 'Tarayıcı',
    'Files': 'Dosyalar',
    'Logs': 'Günlükler',
    'Events': 'Olaylar',
    'Code projection unavailable': 'Kod projeksiyonu kullanılamıyor',
    'No source buffer is exposed by the current Desktop API.': 'Mevcut Desktop API tarafından kaynak tamponu sunulmuyor.',
    'Preview unavailable': 'Önizleme kullanılamıyor',
    'No browser preview projection is exposed.': 'Tarayıcı önizleme projeksiyonu sunulmuyor.',
    'No authoritative live events are available.': 'Yetkili canlı olay bulunmuyor.',
    'STATUS': 'DURUM',
    'Job ID': 'İş Kimliği',
    'Elapsed': 'Geçen süre',
    'Est. finish': 'Tahmini bitiş',
    'Phase': 'Aşama',
    'Active workers': 'Aktif çalışanlar',
    'Status': 'Durum',
    'APPROVALS': 'ONAYLAR',
    'Pending': 'Bekleyen',
    'Approved': 'Onaylanan',
    'Denied': 'Reddedilen',
    'COST & USAGE': 'MALİYET VE KULLANIM',
    'Total cost': 'Toplam maliyet',
    'Budget': 'Bütçe',
    'Token usage': 'Token kullanımı',
    'GPU time': 'GPU süresi',
    'LATEST LOGS': 'SON GÜNLÜKLER',
    'No live event records available.': 'Canlı olay kaydı bulunmuyor.',
    'LATEST ARTIFACTS': 'SON ÇIKTILAR',
    'View all →': 'Tümünü gör →',
    'No verified artifact evidence is available.': 'Doğrulanmış çıktı kanıtı bulunmuyor.',
    'EVIDENCE & VERIFICATION': 'KANIT VE DOĞRULAMA',
    'Verified': 'Kanıt',
    'Policy': 'Kural',
    'Routes': 'Rota',
    'Available': 'Var',
    'Unavailable': 'Yok',
    'OFFLINE': 'ÇEVRİMDIŞI',
    'NO ACTIVE DATA': 'AKTİF VERİ YOK',
    'STATE UNAVAILABLE': 'DURUM KULLANILAMIYOR',
    'Worker': 'Çalışan',
    'Task unavailable': 'Görev kullanılamıyor',
    'Active lease': 'Aktif kiralama',
  };

  static String text(String localeCode, String english) {
    if (localeCode != 'tr') return english;
    return _tr[english] ?? english;
  }
}
