import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Solutions", description: "Explore ILAIOS solution patterns for governed intelligent automation.", alternates: { canonical: "/solutions", languages: { en: "/solutions", tr: "/tr/solutions", "x-default": "/solutions" } } };
const solutions = [
  ["AI operations", "Coordinate model-assisted work behind explicit policy, approvals, validation, and evidence rather than treating model output as authority."],
  ["Software engineering", "Structure engineering tasks as bounded jobs with tool permissions, deterministic checks, review gates, and traceable execution outcomes."],
  ["Security operations", "Support controlled security workflows where sensitive actions remain permission-bound, reviewable, and auditable."],
  ["Business process automation", "Combine deterministic workflow steps with intelligent capabilities while keeping business rules and authorization outside the model."],
  ["Research & knowledge work", "Organize evidence-backed research and synthesis with source traceability, validation, and explicit escalation paths."],
] as const;
export default function Solutions(){return <><section className="shell page-hero"><div className="eyebrow">Solutions</div><h1>Intelligent work, bounded by operational control.</h1><p className="lead">ILAIOS is designed for workflows where automation must remain useful without becoming unaccountable. These solution patterns describe the engineering direction of the platform; they do not claim released customer deployments.</p></section><section className="section"><div className="shell"><div className="section-heading"><div><div className="eyebrow">Use cases</div><h2>Built around governed execution.</h2></div><p className="muted">The same control-plane model can support different operational domains while keeping authority, permissions, evidence, and validation explicit.</p></div><div className="grid two-up">{solutions.map(([title,text])=><article className="card" key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></div></section><section className="section architecture-section"><div className="shell callout"><div><div className="eyebrow">Design principle</div><h2>Models can assist. Policy remains authoritative.</h2></div><div><p className="muted">ILAIOS favors deterministic execution when it is available and uses intelligent capabilities inside explicit boundaries rather than as a substitute for system authority.</p><div className="actions"><Link className="text-link" href="/architecture">See the architecture →</Link><Link className="text-link" href="/trust">Trust Center →</Link></div></div></div></section></>}
