import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata={title:"Trust Center",description:"Review ILAIOS security architecture, access control, data-handling principles, auditability, responsible AI posture, and public claim boundaries.",alternates:{canonical:"/trust",languages:{en:"/trust",tr:"/tr/trust","x-default":"/trust"}}};

const controls=[["Authority stays explicit","Sensitive actions depend on identity, permissions and approval requirements rather than model confidence."],["Evidence stays reviewable","Important execution and validation outcomes are designed to remain inspectable instead of being reduced to a success claim."],["Data access stays bounded","Authorized work is designed around tenant-aware, purpose-bound context rather than unrestricted retrieval."],["Models stay replaceable","A model, provider or tool can contribute to execution without becoming the source of policy or authorization."]] as const;
const boundary=[["Public now","Architecture principles, authority boundaries, evidence-first execution and the verified public contact route."],["Only after verification","Independent certifications, audit reports, formal compliance status, production commitments and customer-specific assurances."],["Not implied","A designed control is not presented as an external audit, certification, contractual guarantee or proof of general availability."]] as const;

export default function Page(){return <>
  <section className="shell page-hero compact-page-hero"><div className="eyebrow">Trust Center</div><h1>Trust starts with evidence, not badges.</h1><p className="lead">ILAIOS separates what the system is designed to enforce from what has been independently verified. Public claims stay inside that boundary.</p></section>
  <section className="section"><div className="shell"><div className="section-heading"><div><div className="eyebrow">What trust means here</div><h2>Control, evidence and clear limits around sensitive work.</h2></div><p className="muted">Security architecture explains the controls. This page explains what those controls do and do not prove publicly.</p></div><div className="principle-directory">{controls.map(([t,x],index)=><article key={t}><span>{String(index+1).padStart(2,"0")}</span><strong>{t}</strong><p>{x}</p></article>)}</div></div></section>
  <section className="section surface-section"><div className="shell"><div className="compact-heading-row"><div><div className="eyebrow">Claim boundary</div><h2>What can be said now, and what requires stronger evidence.</h2></div></div><div className="grid three-up">{boundary.map(([t,x])=><article className="card" key={t}><h3>{t}</h3><p>{x}</p></article>)}</div></div></section>
  <section className="section compact-section"><div className="shell callout"><div><div className="eyebrow">Need the controls?</div><h2>Read the security model or use the verified public contact route.</h2></div><div><p className="muted">No unverified SOC 2, ISO 27001 or equivalent certification claim is published here. Security concerns can be reported through contact@ilaios.com.</p><div className="actions"><Link className="button" href="/security">Security details</Link><a className="button secondary" href="mailto:contact@ilaios.com">contact@ilaios.com</a></div></div></div></section>
</>}
