import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata={title:"Trust Center",description:"Review ILAIOS security architecture, access control, data-handling principles, auditability, responsible AI posture, and public claim boundaries.",alternates:{canonical:"/trust",languages:{en:"/trust",tr:"/tr/trust","x-default":"/trust"}}};

const areas=[["Security architecture","Authority boundaries, least-privilege tool access, backend-enforced control, validation, and evidence are part of the platform architecture direction."],["Data handling","Data access is intended to remain purpose-bound, tenant-aware, and limited to the context required for authorized work."],["Access control","Sensitive operations are designed around explicit identities, permissions, and approval requirements rather than implicit model authority."],["Auditability","Execution state, validation outcomes, and evidence are designed to support reconstruction and review of important actions."],["Responsible AI","Model output is treated as an input to governed systems, not as an unquestioned source of authorization or truth."],["Vulnerability reporting","Security concerns can be reported through the verified public contact channel for triage and responsible handling."]] as const;
const posture=[["Publicly stated now","Architecture principles, security direction, authority boundaries, evidence-first execution, and the current public contact channel."],["Verified before publication","Independent certifications, audit reports, formal compliance status, production availability, service commitments, and customer-specific controls."],["Never inferred from design","A planned control or architecture principle is not represented as a completed certification, external audit, or contractual guarantee."]] as const;
const questions=[["Can an agent authorize itself?","No. Intelligent capability and authorization are separate concerns; sensitive authority remains outside the model."],["Is every action autonomous?","No. Deterministic execution, explicit approvals, and bounded tools are preferred where they provide a safer and clearer path."],["Are certification claims being made?","No unverified SOC 2, ISO 27001, or equivalent certification claim is published here."],["How can a security issue be reported?","Use the verified public contact channel below. A dedicated security mailbox will be published only after that address is verified as an intended public route."]] as const;

export default function Page(){return <>
  <section className="shell page-hero"><div className="eyebrow">Trust Center</div><h1>Trust claims should be inspectable.</h1><p className="lead">ILAIOS separates engineering direction from independently verified status. This Trust Center explains what the architecture is designed to enforce, what can be stated publicly now, and what will only be published after external or operational verification.</p></section>
  <section className="section"><div className="shell"><div className="section-heading"><div><div className="eyebrow">Trust domains</div><h2>Security is a system property, not a badge.</h2></div><p className="muted">The public posture focuses on authority, access, validation, evidence, and explicit claim boundaries.</p></div><div className="grid two-up">{areas.map(([t,x])=><article className="card" key={t}><h3>{t}</h3><p>{x}</p></article>)}</div></div></section>
  <section className="section architecture-section"><div className="shell"><div className="eyebrow">Claim boundary</div><h2>What is stated, what is verified, and what is not implied.</h2><div className="grid">{posture.map(([t,x])=><article className="card" key={t}><h3>{t}</h3><p>{x}</p></article>)}</div></div></section>
  <section className="section"><div className="shell"><div className="eyebrow">Common trust questions</div><h2>Clear answers before stronger claims.</h2><div className="grid two-up">{questions.map(([t,x])=><article className="card" key={t}><h3>{t}</h3><p>{x}</p></article>)}</div></div></section>
  <section className="section compact-section"><div className="shell callout"><div><div className="eyebrow">Security contact</div><h2>Use the verified public channel.</h2></div><div><p className="muted">The only public ILAIOS mailbox verified in the current website source is contact@ilaios.com. Additional Cloudflare-routed aliases will be published by function only after their exact public purpose is verified.</p><div className="actions"><a className="button secondary" href="mailto:contact@ilaios.com">contact@ilaios.com</a><Link className="text-link" href="/security">Security details →</Link></div></div></div></section>
</>}
