import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Capabilities", description: "Explore canonical ILAIOS platform capabilities separately from native finished-product factories and solution outcomes.", alternates: { canonical: "/capabilities", languages: { en: "/capabilities", tr: "/tr/capabilities", "x-default": "/capabilities" } } };
const platform = [["Governed Core","Authority, durable state, validation, evidence and recovery remain outside model narration."],["Identity, Tenant & Policy","Trusted organizational context, permissions, approvals and least-authority execution boundaries."],["Agent & Skill Runtime","Specialist capabilities operate behind contracts, stable machine identity and bounded permissions."],["Workflow & Recovery","Jobs carry dependencies, state, retries, escalation and observable outcomes."],["Knowledge / RAG & Memory","Authorized context, project memory, source provenance, tenant-aware retrieval and grounded synthesis."],["Software Intelligence","Typed source, symbol, dependency and repository context before higher-risk engineering work."],["Validation & Evidence","Deterministic checks and reviewable provenance determine acceptance rather than self-reported success."],["Routing & Providers","Models, tools and providers are replaceable resources selected inside platform policy rather than becoming authority."]] as const;
const factories = [["Web Factory","/factories/web"],["Software Factory","/factories/software"],["App Factory","/factories/app"],["Video / Media Factory","/factories/video"],["Security Factory","/factories/security"],["Research & Data Factory","/factories/research-data"],["Creative & Document Factory","/factories/creative-document"],["Commerce & Growth Factory","/factories/commerce-growth"],["Personal Operations Factory","/factories/personal-operations"]] as const;

export default function Page(){return <>
<section className="shell page-hero"><div className="eyebrow">Canonical capability map</div><h1>Platform capabilities and finished-product factories are related, but not the same thing.</h1><p className="lead">ILAIOS separates the governed platform primitives that make execution trustworthy from the factory workflows that turn those primitives into domain outcomes.</p></section>
<section className="section"><div className="shell split-copy"><div><div className="eyebrow">Platform layer</div><h2>Reusable control, intelligence and execution capabilities.</h2></div><div><p className="lead small">These are canonical capability families. Their current maturity and release state remain evidence-driven.</p><p className="muted">Knowledge/RAG is a shared governed plane, not a production factory. Marketing solution labels do not become architecture identities.</p></div></div></section>
<section className="section architecture-section"><div className="shell"><div className="grid two-up">{platform.map(([t,x],i)=><article className="card" key={t}><div className="eyebrow">{String(i+1).padStart(2,"0")}</div><h3>{t}</h3><p>{x}</p></article>)}</div></div></section>
<section className="section"><div className="shell"><div className="section-heading"><div><div className="eyebrow">Native factories</div><h2>Separate domains. The same governed Core.</h2></div><p className="muted">Software Factory and App Factory are separate canonical factories. A factory name does not imply every function is generally available today.</p></div><div className="grid two-up">{factories.map(([t,href],i)=><Link className="detail-link-card" href={href} key={href}><span>{String(i+1).padStart(2,"0")}</span><h3>{t}</h3><p>Inspect the current foundation, canonical target, boundaries and acceptance model.</p><strong>Explore →</strong></Link>)}</div></div></section>
<section className="section"><div className="shell callout"><div><div className="eyebrow">Outcome layer</div><h2>Business outcomes belong in solutions; canonical identities stay stable here.</h2></div><div className="actions"><Link className="button" href="/factories">All factories</Link><Link className="button secondary" href="/solutions">Solutions</Link></div></div></section>
</>}
