import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata={title:"Architecture",description:"Understand the ILAIOS control-plane architecture, authority boundaries, shared knowledge plane, provider routing and evidence path.",alternates:{canonical:"/architecture",languages:{en:"/architecture",tr:"/tr/architecture","x-default":"/architecture"}}};

const layers=[["01","Clients","Web, Desktop, Mobile, API, CLI and Enterprise Console are governed projections of platform state; a client request is not authority."],["02","Control plane","Backend authority owns policy, tenant context, orchestration, durable state transitions and critical product decisions."],["03","Policy & approvals","Permissions, budgets, risk conditions and required human approval are resolved before bounded execution."],["04","Capability fabric","Factories, agents, skills and deterministic services receive explicit contracts and scope."],["05","Routing & providers","Models, tools and external providers remain replaceable resources selected behind canonical routing and policy."],["06","Validation & evidence","Independent checks, acceptance criteria, provenance and evidence determine whether material results advance."],["07","Delivery & recovery","Accepted outcomes may move to delivery or authorized side effects; failures follow bounded repair, retry or escalation."]] as const;
const boundaries=[["Authority","Request ≠ permission. Model narration, agent identity or tool access cannot silently widen authority."],["Context","Identity, tenant, project, classification and purpose determine what context may participate."],["Execution","Capabilities receive bounded work and the minimum tool scope required for the admitted job."],["Acceptance","Generated output is not final until required validation and evidence conditions pass."],["Recovery","Retry and repair are bounded; unresolved conditions stop or escalate instead of looping indefinitely."]] as const;

export default function Page(){return <>
<section className="shell page-hero"><div className="eyebrow">Architecture</div><h1>One authoritative control plane. Multiple governed capabilities.</h1><p className="lead">ILAIOS keeps user interfaces, intelligent capabilities, provider resources and execution tools separate from the backend authority that governs context, policy, state, validation, evidence and recovery.</p></section>
<section className="section architecture-section"><div className="shell"><div className="section-heading"><div><div className="eyebrow">Authority flow</div><h2>Intent moves down the stack; evidence and accepted state move back up.</h2></div><p className="muted">The architecture prevents presentation, intelligence, execution and permission from collapsing into one opaque component.</p></div><div className="control-stack">{layers.map(([n,t,x],i)=><div key={t}>{i>0&&<div className="stack-connector">controlled boundary ↓</div>}<div className={`stack-layer ${i===1?"authority-layer":""}`}><span>{n}</span><strong>{t}</strong><small>{x}</small></div></div>)}</div></div></section>
<section className="section"><div className="shell split-copy"><div><div className="eyebrow">Knowledge / RAG plane</div><h2>Knowledge informs execution without becoming authority.</h2></div><div><p className="lead small">Authorized context → project memory → source provenance → tenant-aware retrieval → grounded synthesis → evidence.</p><p className="muted">Knowledge/RAG is cross-factory infrastructure. It is deliberately not another finished-product factory and it is not reduced to vector search.</p></div></div></section>
<section className="section evidence-section"><div className="shell"><div className="section-heading"><div><div className="eyebrow">Trust boundaries</div><h2>Capability is not permission.</h2></div><p className="muted">Every meaningful boundary answers what can act, on whose behalf, with what context, and what must be proven before acceptance.</p></div><div className="process-ledger">{boundaries.map(([t,x],i)=><article key={t}><span>{String(i+1).padStart(2,"0")}</span><div><h2>{t}</h2><p>{x}</p></div></article>)}</div></div></section>
<section className="section"><div className="shell split-copy"><div><div className="eyebrow">Provider independence</div><h2>ILAIOS remains the product brain.</h2></div><div><p className="lead small">Models, external providers, editors and tools may change without becoming the source of workflow authority or redefining the user-facing product.</p><p className="muted">Single routing truth, policy gates and capability contracts preserve the system boundary as resources evolve.</p><div className="actions"><Link className="button" href="/core">Explore Core</Link><Link className="button secondary" href="/platform/control-plane">Control plane</Link><Link className="text-link" href="/docs">Documentation →</Link></div></div></div></section>
</>}
