import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import InteractiveExplorer from "../InteractiveExplorer";

export const metadata: Metadata = { title: "Governed AI Operating System", description: "ILAIOS; native finished-product factory'leriyle hedefleri kontrollü ve doğrulanabilir dijital işe dönüştürmek için tasarlanan Governed AI Operating System'dir.", alternates: { canonical: "/tr", languages: { tr: "/tr", en: "/", "x-default": "/" } } };

const audience = [
  ["Kurumlar için", "Tekrarlanan operasyonları, yazılım/web teslimini, araştırmayı, medya üretimini ve güvenlik açısından hassas işleri açık policy, doğrulama ve evidence altında birleştirin.", "/tr/enterprise", "Kurumsal değeri incele"],
  ["Bireysel kullanıcılar için", "Hedeflerinizi araştırma, otomasyon, yazılım/web ve medya workflow'larına dönüştürürken execution durumunu ve kontrolleri görünür tutun.", "/tr/individuals", "Bireysel değeri incele"],
] as const;

const capabilityHighlights = [
  ["Web Factory", "Şirket hedefi ve bilgi mimarisinden responsive geliştirme, erişilebilirlik, SEO, güvenlik ve deployment hazırlığına uzanan web üretim akışı.", "/tr/factories/web"],
  ["Software Factory", "Sınırlandırılmış uygulama, deterministik kontroller, review kapıları ve izlenebilir teslim bağlamıyla yönetilen mühendislik workflow'ları.", "/tr/factories/software"],
  ["Video / Media Factory", "Araştırma, senaryo, scene/shot planlama, asset, ses, render, doğrulama, yayın hazırlığı, recovery ve evidence.", "/tr/factories/video"],
  ["Security Factory", "Yetkili code, secret, supply-chain, infrastructure ve local/test web-security analizini remediation ve bağımsız verification ile sınırlar.", "/tr/factories/security"],
  ["Security & Governance", "Hassas execution etrafında identity, tenant context, permissions, policy, approvals, validation, audit ve evidence.", "/tr/security"],
  ["Ajan Organizasyonu", "Uzman ekipleri kalıcı machine identity, capability contract, izin, verifier ayrımı ve evidence-driven readiness ile yönetir.", "/tr/agents"],
  ["Research & Intelligence", "Kaynak, iddia, belirsizlik ve bilgi ilişkilerini tek seferlik opak sentez yerine yapılandırılmış hale getirme.", "/tr/capabilities"],
  ["Automation & Runtime", "Governed job'lar, scheduler state, execution grant, provider routing, bounded recovery ve gözlemlenebilir sonuçlar.", "/tr/platform/execution"],
] as const;

const flow = [["01","Hedef","İstenen sonucu ve güvenilir bağlamı tanımla."],["02","Yetkilendir","Tenant, policy, izin ve onay gereksinimlerini çöz."],["03","Orkestre et","İşi sınırlandırılmış deterministik veya akıllı adımlara ayır."],["04","Yürüt","Ajan ve araçlar yalnız verilen scope içinde çalışsın."],["05","Doğrula","Güvenlik ve kabul kapıları işin ilerleyip ilerlemeyeceğini belirlesin."],["06","Kanıt","İncelenebilir bağlam, provenance ve validation sonuçlarını koru."],["07","Teslim","Kabul edilen işi teslim, deployment veya yayın için hazırla."],["08","Kurtar","Retry'ları sınırla, hataları görünür kıl ve audit geçmişini koru."]] as const;

export default function Page() { return <>
  <section className="shell hero hero-refresh"><div className="hero-copy"><div className="eyebrow">Kontrollü AI ve dijital operasyon</div><h1>Bir hedefi kontrollü ve doğrulanabilir dijital işe dönüştürün.</h1><p className="lead">ILAIOS yalnız bir chatbot değildir. Kurum ve bireylerin otomasyon, yazılım, web, medya, araştırma ve güvenlik açısından hassas işlerini açık yetki, validation, evidence ve recovery içeren workflow'lara dönüştürmek için tasarlanan genişletilebilir bir platformdur.</p><div className="actions"><Link className="button" href="/tr/capabilities">Yetenekleri incele</Link><Link className="button secondary" href="/tr/core">Core nasıl çalışır?</Link></div><div className="quick-links" aria-label="Hızlı bağlantılar"><Link href="/tr/enterprise">Kurumlar</Link><Link href="/tr/individuals">Bireysel</Link><Link href="/tr/architecture">Mimari</Link><Link href="/tr/security">Güvenlik</Link></div></div><Link className="hero-visual hero-visual-link" href="/tr/architecture" aria-label="ILAIOS mimarisini incele"><Image src="/brand/website-hero.jpg" alt="ILAIOS kontrollü dijital operasyon sistem görseli" width={1920} height={1080} priority sizes="(max-width: 900px) calc(100vw - 32px), 46vw" quality={82} /><span>Sistem modelini incele →</span></Link></section>

  <section className="section"><div className="shell"><div className="section-heading"><div><div className="eyebrow">Kimler için?</div><h2>Farklı kullanıcılar. Faydalı ve kontrollü sonuç için aynı gereksinim.</h2></div><p className="lead small">Ziyaretçi kendi probleminden başlamalı, ILAIOS'un içeride ne yaptığını ve işi nasıl kontrol ettiğini anlayabilmeli; dağıtım açıldığında Desktop veya mobil istemciyi neden kullanacağını net görmeli.</p></div><div className="grid two-up">{audience.map(([title,text,href,label])=><Link className="detail-link-card" href={href} key={href}><span>Kullanıcı</span><h3>{title}</h3><p>{text}</p><strong>{label} →</strong></Link>)}</div></div></section>

  <section className="section architecture-section"><div className="shell"><div className="section-heading"><div><div className="eyebrow">ILAIOS ne yapabilir?</div><h2>Üretim, zekâ, otomasyon ve yönetişim tek ürün mimarisinde.</h2></div><p className="muted">Yetenek sayfaları uygulanmış çekirdekleri ürün mimarisi/geliştirme yönünden ayırır. Henüz yayınlanmamış işlevler genel kullanıma açık servis gibi gösterilmez.</p></div><div className="grid two-up">{capabilityHighlights.map(([title,text,href])=><Link className="detail-link-card" href={href} key={title}><span>Yetenek</span><h3>{title}</h3><p>{text}</p><strong>İncele →</strong></Link>)}</div><div className="actions"><Link className="button" href="/tr/capabilities">Yetenek haritasını aç</Link><Link className="text-link" href="/tr/solutions">Sorunları ve çözümleri incele →</Link></div></div></section>

  <section className="section"><div className="shell"><div className="section-heading"><div><div className="eyebrow">İş nasıl ilerler?</div><h2>İstekten kabul edilmiş sonuca kadar her önemli adımın görevi var.</h2></div><p className="muted">Control plane sistem otoritesidir. İstemciler güvenilir state'i gösterir; araçlar ve akıllı yetenekler verilen scope içinde çalışır; validation ve evidence sonucun ilerleyip ilerlemeyeceğini belirler.</p></div><div className="journey-grid">{flow.map(([n,t,x])=><article className="journey-card" key={n}><span>{n}</span><h3>{t}</h3><p>{x}</p></article>)}</div><div className="actions"><Link className="button secondary" href="/tr/core">ILAIOS Core'u incele</Link><Link className="button secondary" href="/tr/security">Güvenlik modeli</Link><Link className="text-link" href="/tr/platform/evidence">Evidence modeli →</Link></div></div></section>

  <InteractiveExplorer locale="tr" />

  <section className="section evidence-section"><div className="shell evidence-grid"><div><div className="eyebrow">Core neden önemli?</div><h2>Güvenilirlik “sıfır hata” vaadi değil, bir kontrol problemidir.</h2><p className="lead small">Hiçbir karmaşık sistem sıfır hata garantisi veremez. ILAIOS; context, authority, tool access, validation, evidence, confidence, approvals ve bounded recovery mekanizmalarını ayırarak hataların sessiz veya kontrolsüz kalma riskini azaltmayı hedefler.</p><div className="actions"><Link className="button secondary" href="/tr/core">Core temelleri</Link><Link className="text-link" href="/tr/trust">Güven yaklaşımı →</Link></div></div><div className="evidence-panel"><Link className="evidence-row" href="/tr/security/permissions"><span className="evidence-icon">01</span><div><strong>Yetki</strong><small>Hassas işi kim isteyebilir, onaylayabilir veya yürütebilir?</small></div><b>→</b></Link><Link className="evidence-row" href="/tr/platform/validation"><span className="evidence-icon">02</span><div><strong>Doğrulama</strong><small>Kabul öncesi hangi deterministik kontroller geçmeli?</small></div><b>→</b></Link><Link className="evidence-row" href="/tr/platform/evidence"><span className="evidence-icon">03</span><div><strong>Kanıt</strong><small>Execution sonrası hangi incelenebilir bağlam kalır?</small></div><b>→</b></Link></div></div></section>

  <section className="section"><div className="shell callout"><div><div className="eyebrow">Ürün deneyimi</div><h2>Desktop ve mobil, aynı otoriter platformun kontrol yüzeyleridir.</h2><p className="muted">Windows-first Desktop istemcisi; job, approval, progress ve doğrulanmış evidence için backend/control-plane state'inin güvenli projection'ı olarak tasarlanır. Mağaza durumu yalnız gerçek dış dağıtım açıldığında gösterilecektir.</p></div><div className="actions"><Link className="button" href="/tr/docs">Ürün dokümanları</Link><Link className="button secondary" href="/tr/contact">ILAIOS ile iletişim</Link></div></div></section>
</>; }
