import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Governed AI Operating System", description: "ILAIOS; native finished-product factory'leriyle hedefleri kontrollü ve doğrulanabilir dijital işe dönüştürmek için tasarlanan Governed AI Operating System'dir.", alternates: { canonical: "/tr", languages: { tr: "/tr", en: "/", "x-default": "/" } } };

const outcomes = [["Web sitesi","Doğrulanmış finished-site workflow","/tr/factories/web"],["Uygulama","Kontrollü application outcome yönü","/tr/factories/app"],["Yazılım","Sınırlandırılmış engineering ve test evidence","/tr/factories/software"],["Video / medya","Araştırmadan render ve validation'a","/tr/factories/video"],["Araştırma & veri","Provenance-first research workflow","/tr/factories/research-data"],["Doküman","Güvenilir kaynaklarla kontrollü export","/tr/factories/creative-document"],["Growth","Evidence destekli review workflow","/tr/factories/commerce-growth"],["Kişisel operasyon","Review-only operasyon planları","/tr/factories/personal-operations"]] as const;
const flow = [["01","Sonucu tarif et","Model, agent veya provider seçmek yerine neyin bitmesini istediğini söyle."],["02","ILAIOS planlar","Kimlik, tenant, policy ve bağlam çalışma sınırını belirler; iş bounded adımlara ayrılır."],["03","ILAIOS yürütür","Deterministik servisler ve intelligent capabilities yalnız verilen scope içinde çalışır."],["04","ILAIOS doğrular","Testler, acceptance kriterleri, approvals ve evidence sonucun ilerleyip ilerleyemeyeceğini belirler."],["05","Kabul edilmiş sonucu al","Bitmiş iş incelenebilir evidence ile teslim edilir; dış side effect'ler ayrıca yönetilir."]] as const;

export default function Page(){return <>
<section className="shell page-hero"><div className="eyebrow">Governed AI Operating System</div><h1>Tek prompt. Kontrollü execution. Doğrulanmış bitmiş ürün.</h1><p className="lead">ILAIOS; kullanıcı ve kurum hedeflerini native finished-product factory'leri üzerinden kontrollü dijital işe dönüştürmek için tasarlanır. Yetki, validation, evidence ve recovery platform tarafından yönetilir.</p><div className="actions"><Link className="button" href="/tr/capabilities">Sistemi incele</Link><Link className="button secondary" href="/tr/how-it-works">Nasıl çalışır?</Link></div></section>
<section className="section"><div className="shell split-copy"><div><div className="eyebrow">Kullanıcı deneyimi</div><h2>Hedefi söyleyin. İç karmaşıklığı ILAIOS yönetsin.</h2></div><div><p className="lead small">Kanonik ürün yönü kullanıcıya model, provider, agent, skill veya framework seçimini yüklemeden bitmiş bir sonuca ilerlemektir.</p><p className="muted">Kanonik yön ile bugün gerçekten implemented, verified, deployed veya genel kullanıma açık olan capability'ler ayrı tutulur.</p></div></div></section>
<section className="section architecture-section"><div className="shell"><div className="section-heading"><div><div className="eyebrow">Outcome protocol</div><h2>Yüzeyde basit. Altta açık authority ve acceptance.</h2></div><p className="muted">Control plane sistem otoritesidir; model çıktısı tek başına izin veya kabul değildir.</p></div><div className="journey-grid">{flow.map(([n,t,x])=><article className="journey-card" key={n}><span>{n}</span><h3>{t}</h3><p>{x}</p></article>)}</div></div></section>
<section className="section"><div className="shell"><div className="section-heading"><div><div className="eyebrow">Ne bitirebilirsiniz?</div><h2>Araçtan değil, sonuçtan başlayın.</h2></div><p className="muted">Factory adı maturity veya genel kullanıma açıklık iddiası değildir. Her detail page mevcut foundation ile target workflow'u ayırır.</p></div><div className="grid two-up">{outcomes.map(([t,x,href])=><Link className="detail-link-card" href={href} key={href}><span>Outcome</span><h3>{t}</h3><p>{x}</p><strong>İncele →</strong></Link>)}</div></div></section>
<section className="section evidence-section"><div className="shell split-copy"><div><div className="eyebrow">Knowledge / RAG & Memory</div><h2>Factory değil; factory'ler arasında çalışan governed knowledge plane.</h2></div><div><p className="lead small">Authorized context, project memory, source provenance, tenant-aware retrieval ve grounded synthesis evidence ile bağlı tutulur. Knowledge yalnız vector search değildir.</p><div className="actions"><Link className="text-link" href="/tr/core">Core ve context modelini incele →</Link></div></div></div></section>
<section className="section"><div className="shell callout"><div><div className="eyebrow">Provider bağımsızlığı</div><h2>Ürün beyni ILAIOS'tur; model, araç ve provider'lar değiştirilebilir kaynaklardır.</h2><p className="muted">Desktop, mobile, web ve diğer istemciler aynı authoritative backend/control-plane state'inin kontrollü projection'larıdır.</p></div><div className="actions"><Link className="button" href="/tr/architecture">Mimari</Link><Link className="button secondary" href="/tr/factories">Factory'ler</Link></div></div></section>
</>}
