import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "ILAIOS | Kontrollü Akıllı Sistemler",
  description: "ILAIOS; açık yetki sınırları, doğrulanabilir yürütme ve güvenlik odaklı operasyonlar için akıllı otomasyon altyapısı geliştirir.",
  alternates: { canonical: "/tr", languages: { tr: "/tr", en: "/", "x-default": "/" } },
};

const pillars=[["Yönetilebilir","Kritik işlemler açık politikalar, izinler, onaylar ve gözlemlenebilir kontrol yollarıyla sınırlandırılır."],["Doğrulanabilir","Yürütme; kanıt, doğrulama, denetlenebilirlik ve mümkün olan yerde deterministik davranış etrafında tasarlanır."],["Birleştirilebilir","İstemciler, servisler, ajanlar ve iş akışları sunum katmanına bağımlı olmak yerine kalıcı sözleşmelerle ayrılır."]] as const;
export default function Page(){return <><section className="shell page-hero"><div className="eyebrow">Akıllı sistemler. Kontrollü yürütme.</div><h1>Kontrol edebileceğiniz otonomi.</h1><p className="lead">ILAIOS; açık kontrol sınırları, doğrulanabilir yürütme ve güvenlik odaklı operasyonlarla akıllı otomasyon altyapısı geliştiriyor.</p><div className="actions"><Link className="button" href="/tr/platform">Platformu inceleyin</Link><Link className="button secondary" href="/tr/about">ILAIOS neden var?</Link></div></section><section className="section"><div className="shell"><div className="eyebrow">Tasarım ilkeleri</div><h2>Kontrolden vazgeçmeden otonomi.</h2><div className="grid">{pillars.map(([t,d])=><article className="card" key={t}><h3>{t}</h3><p>{d}</p></article>)}</div></div></section><section className="section architecture-section"><div className="shell"><div className="section-heading"><div><div className="eyebrow">Kontrol mimarisi</div><h2>Niyetten kanıta uzanan yönetilen bir yol.</h2></div><p className="lead small">Kullanıcı arayüzü sistem otoritesi değildir. Politika, izin, yürütme ve doğrulama kararları kontrol katmanında kalır.</p></div><div className="control-stack"><div className="stack-layer"><span>İSTEMCİ KATMANI</span><strong>Masaüstü · Mobil · Web</strong><small>Hedefler, onaylar, gözlemlenebilirlik ve teslim</small></div><div className="stack-connector">↓ yönetilen istekler / gözlemlenebilir sonuçlar ↑</div><div className="stack-layer authority-layer"><span>YETKİLİ KONTROL KATMANI</span><strong>Politika · Orkestrasyon · İzinler · Doğrulama</strong><small>Karar yetkisi sunum istemcilerinin dışında kalır</small></div><div className="stack-connector">↓ sınırlandırılmış yürütme / kanıt ↑</div><div className="stack-layer"><span>YÜRÜTME KATMANI</span><strong>Araçlar · Servisler · Ajanlar · İş Akışları</strong><small>Önce deterministik yollar; uygun olduğunda akıllı yetenekler</small></div></div></div></section><section className="section evidence-section"><div className="shell"><div className="eyebrow">Kanıt ve güvenlik</div><h2>Güven, kontrol ve kanıttan gelmeli.</h2><p className="lead small">Hassas işlemler; izinlere, onay kapılarına, doğrulamaya ve denetlenebilir kanıta dayanacak şekilde tasarlanır.</p><div className="actions"><Link className="text-link" href="/tr/security">Güvenlik yaklaşımını inceleyin →</Link></div></div></section></>}
