import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Yetenekler", description: "Kanonik ILAIOS platform yeteneklerini native finished-product factory'lerinden ve solution outcome'larından ayrı inceleyin.", alternates: { canonical: "/tr/capabilities", languages: { tr: "/tr/capabilities", en: "/capabilities", "x-default": "/capabilities" } } };
const platform = [["Governed Core","Yetki, durable state, validation, evidence ve recovery model anlatımının dışında kalır."],["Identity, Tenant & Policy","Güvenilir organizasyon bağlamı, izinler, onaylar ve minimum-yetki execution sınırları."],["Agent & Skill Runtime","Uzman capability'ler contract, kalıcı machine identity ve bounded permissions arkasında çalışır."],["Workflow & Recovery","Job'lar dependency, state, retry, escalation ve gözlemlenebilir sonuç taşır."],["Knowledge / RAG & Memory","Authorized context, project memory, source provenance, tenant-aware retrieval ve grounded synthesis."],["Software Intelligence","Daha riskli engineering öncesi typed source, symbol, dependency ve repository bağlamı."],["Validation & Evidence","Deterministik kontroller ve incelenebilir provenance kabulü self-reported success yerine belirler."],["Routing & Providers","Model, araç ve provider'lar platform policy içinde seçilen değiştirilebilir kaynaklardır; otorite değildir."]] as const;
const factories = [["Web Factory","/tr/factories/web"],["Software Factory","/tr/factories/software"],["App Factory","/tr/factories/app"],["Video / Media Factory","/tr/factories/video"],["Security Factory","/tr/factories/security"],["Research & Data Factory","/tr/factories/research-data"],["Creative & Document Factory","/tr/factories/creative-document"],["Commerce & Growth Factory","/tr/factories/commerce-growth"],["Personal Operations Factory","/tr/factories/personal-operations"]] as const;

export default function Page(){return <>
<section className="shell page-hero"><div className="eyebrow">Kanonik yetenek haritası</div><h1>Platform yetenekleri ile finished-product factory'leri bağlantılıdır; aynı şey değildir.</h1><p className="lead">ILAIOS güvenilir execution sağlayan platform primitive'lerini, bu primitive'leri domain sonuçlarına dönüştüren factory workflow'larından ayırır.</p></section>
<section className="section"><div className="shell split-copy"><div><div className="eyebrow">Platform katmanı</div><h2>Tekrar kullanılabilir kontrol, intelligence ve execution yetenekleri.</h2></div><div><p className="lead small">Bunlar kanonik capability aileleridir. Mevcut maturity ve release state evidence-driven kalır.</p><p className="muted">Knowledge/RAG ortak governed plane'dir; production factory değildir. Marketing solution isimleri architecture identity haline gelmez.</p></div></div></section>
<section className="section architecture-section"><div className="shell"><div className="grid two-up">{platform.map(([t,x],i)=><article className="card" key={t}><div className="eyebrow">{String(i+1).padStart(2,"0")}</div><h3>{t}</h3><p>{x}</p></article>)}</div></div></section>
<section className="section"><div className="shell"><div className="section-heading"><div><div className="eyebrow">Native factory'ler</div><h2>Ayrı domain'ler. Aynı governed Core.</h2></div><p className="muted">Software Factory ile App Factory ayrı kanonik factory'lerdir. Bir factory adı tüm fonksiyonların bugün genel kullanıma açık olduğu anlamına gelmez.</p></div><div className="grid two-up">{factories.map(([t,href],i)=><Link className="detail-link-card" href={href} key={href}><span>{String(i+1).padStart(2,"0")}</span><h3>{t}</h3><p>Current foundation, canonical target, boundaries ve acceptance modelini inceleyin.</p><strong>İncele →</strong></Link>)}</div></div></section>
<section className="section"><div className="shell callout"><div><div className="eyebrow">Outcome katmanı</div><h2>İş sonuçları solutions altında; kanonik identity'ler burada stabil kalır.</h2></div><div className="actions"><Link className="button" href="/tr/factories">Tüm factory'ler</Link><Link className="button secondary" href="/tr/solutions">Çözümler</Link></div></div></section>
</>}
