import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import InteractiveExplorer from "./InteractiveExplorer";

export const metadata: Metadata = { title: "Governed Intelligent Automation", description: "ILAIOS builds governed infrastructure for intelligent automation and autonomous operations.", alternates: { canonical: "/", languages: { en: "/", tr: "/tr", "x-default": "/" } } };

const pathways = [
  ["How is control preserved?", "See the system boundary between clients, control-plane authority, execution, and evidence.", "/architecture", "Architecture"],
  ["Where can it be applied?", "Explore solution patterns for AI operations, engineering, security, business processes, and research.", "/solutions", "Solutions"],
  ["How is sensitive work governed?", "Review permissions, approvals, auditability, and the public trust posture.", "/trust", "Trust Center"],
  ["How do I evaluate the model?", "Read the public system, security, execution, agent, and evidence documentation overview.", "/docs", "Documentation"],
] as const;

const destinations = [
  ["Platform", "Control, execution, and evidence as one governed operating model.", "/platform"], ["Architecture", "A clear map of authority and system boundaries.", "/architecture"], ["Solutions", "Use-case patterns without invented customer claims.", "/solutions"], ["Security", "Permissions, approvals, audit context, and fail-closed design.", "/security"], ["Trust Center", "Public security posture and explicit claim boundaries.", "/trust"], ["Resources", "Short technical perspectives behind the product direction.", "/resources"],
] as const;

export default function Home() { return <>
  <section className="shell hero hero-refresh"><div className="hero-copy"><div className="eyebrow">Governed intelligent automation</div><h1>Move intelligent work from suggestion to controlled execution.</h1><p className="lead">ILAIOS is developing infrastructure where policy, permissions, validation, and evidence remain explicit while intelligent capabilities assist operational work.</p><div className="actions"><Link className="button" href="#how-it-works">Explore interactively</Link><Link className="button secondary" href="/platform">Platform overview</Link></div><div className="quick-links" aria-label="Quick links"><Link href="/architecture">Architecture</Link><Link href="/solutions">Solutions</Link><Link href="/trust">Trust</Link><Link href="/docs">Docs</Link></div></div><Link className="hero-visual hero-visual-link" href="/architecture" aria-label="Explore ILAIOS architecture"><Image src="/brand/website-hero.jpg" alt="ILAIOS governed automation system visual" width={1920} height={1080} priority sizes="(max-width: 900px) calc(100vw - 32px), 46vw" quality={82} /><span>Explore the system model →</span></Link></section>
  <section className="section question-section"><div className="shell"><div className="section-heading compact-heading"><div><div className="eyebrow">Start with your question</div><h2>Every major idea has a clear next step.</h2></div><p className="lead small">The site now favors full-card navigation and in-page interaction instead of decorative blocks that lead nowhere.</p></div><div className="pathway-grid">{pathways.map(([title,text,href,label]) => <Link className="pathway-card" href={href} key={href}><span>{label}</span><h3>{title}</h3><p>{text}</p><strong>Explore →</strong></Link>)}</div></div></section>
  <InteractiveExplorer locale="en" />
  <section className="section evidence-section"><div className="shell evidence-grid"><div><div className="eyebrow">Evidence & security</div><h2>Trust should be inspectable.</h2><p className="lead small">Sensitive work is designed around explicit authority, approval requirements, validation, and evidence—not around a model simply claiming success.</p><div className="actions"><Link className="button secondary" href="/security">Security model</Link><Link className="text-link" href="/trust">Public trust posture →</Link></div></div><div className="evidence-panel"><Link className="evidence-row" href="/security/permissions"><span className="evidence-icon">01</span><div><strong>Permissions</strong><small>Who may request or execute sensitive work?</small></div><b>→</b></Link><Link className="evidence-row" href="/security/approvals"><span className="evidence-icon">02</span><div><strong>Approvals</strong><small>Which actions require independent authorization?</small></div><b>→</b></Link><Link className="evidence-row" href="/platform/evidence"><span className="evidence-icon">03</span><div><strong>Evidence</strong><small>What remains observable after execution?</small></div><b>→</b></Link></div></div></section>
  <section className="section"><div className="shell"><div className="eyebrow">Explore ILAIOS</div><h2>A connected site, not a collection of dead ends.</h2><div className="destination-grid">{destinations.map(([title,text,href]) => <Link className="destination-card" href={href} key={href}><div><span>Explore</span><h3>{title}</h3><p>{text}</p></div><strong aria-hidden="true">↗</strong></Link>)}</div></div></section>
</>; }
