import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Governed AI Operating System", description: "ILAIOS is a governed AI operating system with native finished-product factories for controlled, verifiable digital work.", alternates: { canonical: "/", languages: { en: "/", tr: "/tr", "x-default": "/" } } };

const outcomes = [["Website","Verified finished-site workflow","/factories/web"],["Application","Governed application-outcome direction","/factories/app"],["Software","Bounded engineering with test evidence","/factories/software"],["Video / media","Research through render and validation","/factories/video"],["Research & data","Provenance-first research workflow","/factories/research-data"],["Document","Trusted-source composition and controlled export","/factories/creative-document"],["Growth","Evidence-backed review workflow","/factories/commerce-growth"],["Personal operations","Review-only operation plans","/factories/personal-operations"]] as const;
const flow = [["01","Describe the outcome","Say what should be finished instead of selecting models, agents or providers."],["02","ILAIOS plans","Identity, tenant, policy and context establish the boundary; work is decomposed into bounded steps."],["03","ILAIOS executes","Deterministic services and intelligent capabilities operate only inside granted scopes."],["04","ILAIOS validates","Tests, acceptance criteria, approvals and evidence determine whether the result may advance."],["05","Receive accepted work","Finished work is delivered with reviewable evidence; external side effects remain separately governed."]] as const;
const surfaces = [["Web","Public product and documentation surface","PUBLIC"],["Desktop","Windows-first governed client projection","DISTRIBUTION STATE SEPARATE"],["Mobile","Mobile projection of the same backend authority","PRODUCT DIRECTION"],["API","Programmatic governed interface","PRODUCT DIRECTION"],["CLI","Operator and engineering interface","PRODUCT DIRECTION"],["Enterprise Console","Organizational administration and control surface","PRODUCT DIRECTION"]] as const;

export default function Home(){return <>
<section className="shell page-hero"><div className="eyebrow">Governed AI Operating System</div><h1>One prompt. Governed execution. Verified finished product.</h1><p className="lead">ILAIOS is designed to turn user and organization goals into controlled digital work across native finished-product factories. Authority, validation, evidence and recovery remain governed by the platform.</p><div className="actions"><Link className="button" href="/capabilities">Explore the system</Link><Link className="button secondary" href="/how-it-works">How it works</Link></div></section>
<section className="section"><div className="shell split-copy"><div><div className="eyebrow">User experience</div><h2>State the goal. Let ILAIOS govern the internal complexity.</h2></div><div><p className="lead small">The canonical product direction moves toward a finished result without requiring users to choose models, providers, agents, skills or internal frameworks.</p><p className="muted">Canonical direction remains separate from what is currently implemented, verified, deployed or generally available.</p></div></div></section>
<section className="section architecture-section"><div className="shell"><div className="section-heading"><div><div className="eyebrow">Outcome protocol</div><h2>Simple at the surface. Explicit authority and acceptance underneath.</h2></div><p className="muted">The control plane is authoritative; model output alone is neither permission nor acceptance.</p></div><div className="journey-grid">{flow.map(([n,t,x])=><article className="journey-card" key={n}><span>{n}</span><h3>{t}</h3><p>{x}</p></article>)}</div></div></section>
<section className="section"><div className="shell"><div className="section-heading"><div><div className="eyebrow">What can you finish?</div><h2>Start with the outcome, not the tool.</h2></div><p className="muted">A factory name does not claim maturity or general availability. Detail pages separate current foundations from target workflows.</p></div><div className="grid two-up">{outcomes.map(([t,x,href])=><Link className="detail-link-card" href={href} key={href}><span>Outcome</span><h3>{t}</h3><p>{x}</p><strong>Explore →</strong></Link>)}</div></div></section>
<section className="section evidence-section"><div className="shell split-copy"><div><div className="eyebrow">Knowledge / RAG & Memory</div><h2>A governed knowledge plane shared across factories.</h2></div><div><p className="lead small">Authorized context, project memory, source provenance, tenant-aware retrieval and grounded synthesis remain connected to evidence. Knowledge is more than vector search.</p><div className="actions"><Link className="text-link" href="/core">Explore Core and context →</Link></div></div></div></section>
<section className="section"><div className="shell"><div className="section-heading"><div><div className="eyebrow">Product surfaces</div><h2>Different clients. The same authoritative platform.</h2></div><p className="muted">A surface can be part of the canonical architecture without being publicly distributed today. Availability is shown only when externally verified.</p></div><div className="process-ledger">{surfaces.map(([t,x,s],i)=><article key={t}><span>{String(i+1).padStart(2,"0")}</span><div><h2>{t}</h2><p>{x} · {s}</p></div></article>)}</div></div></section>
<section className="section"><div className="shell callout"><div><div className="eyebrow">Provider independence</div><h2>ILAIOS remains the product brain; models, tools and providers are replaceable resources.</h2><p className="muted">Desktop, mobile, web and other clients are governed projections of the same authoritative backend/control-plane state.</p></div><div className="actions"><Link className="button" href="/architecture">Architecture</Link><Link className="button secondary" href="/factories">Factories</Link></div></div></section>
</>}
