import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import InteractiveExplorer from "./InteractiveExplorer";

export const metadata: Metadata = { title: "Governed AI & Digital Operations Platform", description: "ILAIOS turns organizational and individual goals into governed, verifiable workflows across automation, software, web, media, research and security.", alternates: { canonical: "/", languages: { en: "/", tr: "/tr", "x-default": "/" } } };

const audience = [
  ["For enterprises", "Unify repetitive operations, software/web delivery, research, media and security-sensitive workflows under explicit policy, validation and evidence.", "/enterprise", "See enterprise value"],
  ["For individuals", "Turn goals into structured research, automation, software/web and media workflows while keeping execution state and controls visible.", "/individuals", "See individual value"],
] as const;

const capabilityHighlights = [
  ["Web Factory", "From business goal and information architecture through responsive implementation, accessibility, SEO, security and deployment preparation.", "/factories/web"],
  ["Software Factory", "Governed engineering workflows with bounded implementation, deterministic checks, review gates and traceable delivery context.", "/factories/software"],
  ["Video / Media Factory", "Research, script, scene/shot planning, assets, voice, render, validation, publishing preparation, recovery and evidence.", "/factories/video"],
  ["Security Factory", "Authorized defensive code, secret, supply-chain, infrastructure and local/test web-security analysis with remediation and independent verification.", "/factories/security"],
  ["Security & Governance", "Identity, tenant context, permissions, policy, approvals, validation, audit and evidence around sensitive execution.", "/security"],
  ["Agent Organization", "Specialist teams behind stable machine identities, capability contracts, permissions, verifier separation and evidence-driven readiness.", "/agents"],
  ["Research & Intelligence", "Structured sources, claims, uncertainty and knowledge relationships instead of opaque one-shot synthesis.", "/capabilities"],
  ["Automation & Runtime", "Governed jobs, scheduler state, execution grants, provider routing, bounded recovery and observable outcomes.", "/platform/execution"],
] as const;

const flow = [["01","Goal","Define the outcome and trusted context."],["02","Authorize","Resolve tenant, policy, permissions and approvals."],["03","Orchestrate","Break work into bounded deterministic or intelligent steps."],["04","Execute","Agents and tools act only inside granted scopes."],["05","Validate","Security and acceptance gates decide whether work advances."],["06","Evidence","Keep reviewable context, provenance and validation results."],["07","Deliver","Prepare accepted work for delivery, deployment or publishing."],["08","Recover","Bound retries, expose failures and preserve audit history."]] as const;

export default function Home() { return <>
  <section className="shell hero hero-refresh"><div className="hero-copy"><div className="eyebrow">AI & digital operations, governed</div><h1>Turn a goal into controlled, verifiable digital work.</h1><p className="lead">ILAIOS is an extensible platform for organizations and individuals who need more than a chatbot: it structures automation, software, web, media, research and security-sensitive work as governed workflows with explicit authority, validation, evidence and recovery.</p><div className="actions"><Link className="button" href="/capabilities">Explore capabilities</Link><Link className="button secondary" href="/core">How the Core works</Link></div><div className="quick-links" aria-label="Quick links"><Link href="/enterprise">Enterprises</Link><Link href="/individuals">Individuals</Link><Link href="/architecture">Architecture</Link><Link href="/security">Security</Link></div></div><Link className="hero-visual hero-visual-link" href="/architecture" aria-label="Explore ILAIOS architecture"><Image src="/brand/website-hero.jpg" alt="ILAIOS governed digital operations system visual" width={1920} height={1080} priority sizes="(max-width: 900px) calc(100vw - 32px), 46vw" quality={82} /><span>Explore the system model →</span></Link></section>

  <section className="section"><div className="shell"><div className="section-heading"><div><div className="eyebrow">Who is it for?</div><h2>Different users. The same requirement for useful, controlled outcomes.</h2></div><p className="lead small">A visitor should be able to start from their problem, understand what ILAIOS does inside, and see how work is controlled before deciding to use a Desktop or mobile client when distribution is available.</p></div><div className="grid two-up">{audience.map(([title,text,href,label])=><Link className="detail-link-card" href={href} key={href}><span>Audience</span><h3>{title}</h3><p>{text}</p><strong>{label} →</strong></Link>)}</div></div></section>

  <section className="section architecture-section"><div className="shell"><div className="section-heading"><div><div className="eyebrow">What ILAIOS can do</div><h2>Production, intelligence, automation and governance in one product architecture.</h2></div><p className="muted">Capability pages distinguish implemented foundations from product architecture and development direction. Unreleased functions are not represented as generally available services.</p></div><div className="grid two-up">{capabilityHighlights.map(([title,text,href])=><Link className="detail-link-card" href={href} key={title}><span>Capability</span><h3>{title}</h3><p>{text}</p><strong>Explore →</strong></Link>)}</div><div className="actions"><Link className="button" href="/capabilities">View the capability map</Link><Link className="text-link" href="/solutions">Explore problems and solutions →</Link></div></div></section>

  <section className="section"><div className="shell"><div className="section-heading"><div><div className="eyebrow">How work moves</div><h2>From request to accepted outcome, every important step has a role.</h2></div><p className="muted">The control plane remains authoritative. Clients show trusted state; tools and intelligent capabilities operate within granted scopes; validation and evidence decide whether a result advances.</p></div><div className="journey-grid">{flow.map(([n,t,x])=><article className="journey-card" key={n}><span>{n}</span><h3>{t}</h3><p>{x}</p></article>)}</div><div className="actions"><Link className="button secondary" href="/core">Explore ILAIOS Core</Link><Link className="button secondary" href="/security">Security model</Link><Link className="text-link" href="/platform/evidence">Evidence model →</Link></div></div></section>

  <InteractiveExplorer locale="en" />

  <section className="section evidence-section"><div className="shell evidence-grid"><div><div className="eyebrow">Why the Core matters</div><h2>Reliability is a control problem, not a promise of zero errors.</h2><p className="lead small">No complex system can guarantee that errors never occur. ILAIOS instead separates context, authority, tool access, validation, evidence, confidence, approvals and bounded recovery so failures are less likely to remain silent or uncontrolled.</p><div className="actions"><Link className="button secondary" href="/core">Core foundations</Link><Link className="text-link" href="/trust">Public trust posture →</Link></div></div><div className="evidence-panel"><Link className="evidence-row" href="/security/permissions"><span className="evidence-icon">01</span><div><strong>Authority</strong><small>Who may request, approve or execute sensitive work?</small></div><b>→</b></Link><Link className="evidence-row" href="/platform/validation"><span className="evidence-icon">02</span><div><strong>Validation</strong><small>What deterministic checks must pass before acceptance?</small></div><b>→</b></Link><Link className="evidence-row" href="/platform/evidence"><span className="evidence-icon">03</span><div><strong>Evidence</strong><small>What reviewable context remains after execution?</small></div><b>→</b></Link></div></div></section>

  <section className="section"><div className="shell callout"><div><div className="eyebrow">Product experience</div><h2>Desktop and mobile are control surfaces for the same authoritative platform.</h2><p className="muted">The Windows-first Desktop client is designed as a secure projection of backend/control-plane state for jobs, approvals, progress and verified evidence. Store availability will only be shown when external distribution is actually live.</p></div><div className="actions"><Link className="button" href="/docs">Read product documentation</Link><Link className="button secondary" href="/contact">Contact ILAIOS</Link></div></div></section>
</>; }
