import Link from "next/link";

type Locale = "en" | "tr";
type Mode = "enterprise" | "individuals" | "capabilities" | "core";

type Card = { title: string; text: string; points: string[] };

const capabilityCards: Record<Locale, Card[]> = {
  en: [
    { title: "Governed Core", text: "Turns a goal into bounded work while keeping authority, validation, evidence, and recovery outside model narration.", points: ["Validated context and explicit authority", "Tool gateway and permission boundaries", "Validation, evidence, confidence and recovery"] },
    { title: "Agent & Skill Runtime", text: "Coordinates specialized intelligent capabilities behind contracts and permissions instead of treating an agent name as authority.", points: ["Role/capability separation", "Allowed callers and targets", "Deterministic execution when sufficient"] },
    { title: "Workflow & Recovery", text: "Represents work as jobs with dependencies, states, retries, approvals and observable outcomes.", points: ["Scheduler and dependency order", "Bounded retry and failure classification", "Human approval where required"] },
    { title: "Identity, Tenant & Policy", text: "Keeps organizational context, permissions and governance explicit so a client cannot silently widen authority.", points: ["Tenant-scoped context", "Policy and authorization gates", "Audit-ready security events"] },
    { title: "Knowledge & Intelligence", text: "Organizes validated project knowledge, relationships and research so decisions can stay connected to sources and context.", points: ["Knowledge graph direction", "Research and evidence packets", "Source/provenance-aware synthesis"] },
    { title: "Code & Software Intelligence", text: "Inspects repositories and software structure through typed, deterministic analysis before higher-risk changes or delivery steps.", points: ["Source and symbol analysis", "Dependency/project context", "Quality gates before acceptance"] },
    { title: "Web Factory", text: "Transforms a business goal into a structured website production workflow: requirements, information architecture, content, implementation, validation and deployment preparation.", points: ["Responsive web and mobile design together", "Truthful product/company content", "Accessibility, SEO, security and performance gates"] },
    { title: "App / Software Factory", text: "Structures application work as governed engineering jobs rather than an unconstrained one-shot code generation request.", points: ["Plan and bounded implementation", "Deterministic tests and review gates", "Traceable delivery evidence"] },
    { title: "Video / Media Factory", text: "Automates the full media lifecycle from research and script through scene/shot planning, assets, audio, render, validation and publishing preparation.", points: ["Provider-independent generation", "Technical and content validation", "Scheduling, recovery, evidence and cost controls"] },
    { title: "Research & Data", text: "Builds structured research workflows where claims, sources, uncertainty and validation remain visible.", points: ["Evidence-backed research packets", "Source references and risk flags", "Escalation when confidence is insufficient"] },
    { title: "Enterprise Intelligence", text: "Connects operational context, knowledge and governed execution so teams can move from questions to controlled outcomes.", points: ["Context-aware assistance", "Workflow-linked intelligence", "Reviewable decisions and outputs"] },
    { title: "Automation & Personal Operations", text: "Supports repeatable personal or team workflows while keeping schedules, state, permissions and execution history observable.", points: ["Recurring job orchestration", "Cross-device client projection", "State, evidence and recovery"] },
    { title: "Security & Governance", text: "Applies permission boundaries, approvals, validation, audit and evidence around sensitive work instead of relying on prompt instructions alone.", points: ["Least-authority design", "Independent approval paths", "Traceability from request to result"] },
  ],
  tr: [
    { title: "Kontrollü Çekirdek", text: "Bir hedefi kontrollü işe dönüştürür; yetki, doğrulama, kanıt ve kurtarma model anlatımının dışında tutulur.", points: ["Doğrulanmış bağlam ve açık yetki", "Tool gateway ve izin sınırları", "Doğrulama, kanıt, güven ve kurtarma"] },
    { title: "Ajan & Skill Runtime", text: "Uzman akıllı yetenekleri sözleşme ve izinlerle koordine eder; ajan adı tek başına sistem otoritesi değildir.", points: ["Rol/yetenek ayrımı", "İzinli çağıran ve hedefler", "Yeterli olduğunda deterministik yürütme"] },
    { title: "Workflow & Recovery", text: "İşi bağımlılıkları, durumları, retry, onay ve gözlemlenebilir sonuçları olan job'lar şeklinde temsil eder.", points: ["Zamanlama ve bağımlılık sırası", "Sınırlı retry ve hata sınıflandırması", "Gerektiğinde insan onayı"] },
    { title: "Kimlik, Tenant & Policy", text: "Organizasyon bağlamını, izinleri ve yönetişimi açık tutar; istemci otoritesini sessizce genişletemez.", points: ["Tenant kapsamlı bağlam", "Policy ve authorization kapıları", "Denetime uygun güvenlik olayları"] },
    { title: "Bilgi & Zekâ", text: "Doğrulanmış proje bilgisi, ilişkiler ve araştırmayı düzenleyerek kararları kaynak ve bağlamla bağlı tutmayı hedefler.", points: ["Knowledge graph yönü", "Research/evidence paketleri", "Kaynak ve provenance farkındalığı"] },
    { title: "Kod & Yazılım Zekâsı", text: "Daha riskli değişikliklerden önce repository ve yazılım yapısını typed, deterministik analizle inceler.", points: ["Kaynak ve symbol analizi", "Dependency/proje bağlamı", "Kabul öncesi kalite kapıları"] },
    { title: "Web Factory", text: "Şirket hedefini gereksinim, bilgi mimarisi, içerik, geliştirme, doğrulama ve deployment hazırlığı olan web üretim akışına dönüştürür.", points: ["Web ve mobil responsive tasarım birlikte", "Doğru ürün/şirket içeriği", "Erişilebilirlik, SEO, güvenlik ve performans kapıları"] },
    { title: "App / Software Factory", text: "Uygulama geliştirmeyi kontrolsüz tek seferlik kod üretimi yerine yönetilen mühendislik job'ları olarak yapılandırır.", points: ["Plan ve sınırlandırılmış uygulama", "Deterministik test ve review kapıları", "İzlenebilir teslim kanıtı"] },
    { title: "Video / Media Factory", text: "Araştırma ve senaryodan sahne/shot planına, asset, ses, render, doğrulama ve yayın hazırlığına kadar medya yaşam döngüsünü otomatikleştirir.", points: ["Provider bağımsız üretim", "Teknik ve içerik doğrulama", "Zamanlama, recovery, kanıt ve maliyet kontrolleri"] },
    { title: "Araştırma & Veri", text: "İddiaların, kaynakların, belirsizliğin ve doğrulamanın görünür kaldığı yapılandırılmış araştırma akışları kurar.", points: ["Kanıt destekli research packet", "Kaynak referansı ve risk işaretleri", "Yetersiz güven seviyesinde escalation"] },
    { title: "Enterprise Intelligence", text: "Operasyon bağlamını, bilgiyi ve kontrollü execution'ı birleştirerek ekipleri sorudan denetlenebilir sonuca taşır.", points: ["Bağlama duyarlı yardım", "Workflow bağlantılı zekâ", "İncelenebilir karar ve çıktı"] },
    { title: "Automation & Personal Operations", text: "Tekrarlanan kişisel veya ekip işlerini schedule, state, izin ve execution geçmişi görünür şekilde yürütmeyi destekler.", points: ["Tekrarlanan job orchestration", "Cihazlar arası istemci projection", "State, evidence ve recovery"] },
    { title: "Security & Governance", text: "Hassas işlerin çevresine prompt talimatı yerine izin sınırları, onay, doğrulama, audit ve evidence koyar.", points: ["Minimum yetki yaklaşımı", "Bağımsız onay yolları", "İstekten sonuca izlenebilirlik"] },
  ],
};

const operating: Record<Locale, [string,string,string][]> = {
  en: [["01","Goal & context","The user or organization states the desired outcome; identity, tenant and trusted context define the operating boundary."],["02","Policy & authorization","Permissions, tool scopes, targets, budget and approval requirements are resolved before sensitive execution."],["03","Plan & orchestrate","The job is decomposed into ordered, bounded steps and routed to deterministic services or intelligent capabilities."],["04","Execute","Agents/tools act only inside granted scopes; clients remain projections of backend authority."],["05","Validate","Deterministic checks, security gates and acceptance criteria decide whether an output can advance."],["06","Evidence & approval","Meaningful events, validation results and provenance are retained; independent approval is required where policy says so."],["07","Deliver & monitor","Accepted results are delivered or prepared for deployment/publishing, then monitored for status and failure."],["08","Recover & audit","Retryable failures follow bounded recovery; non-retryable failures stop or escalate with a reviewable trail."]],
  tr: [["01","Hedef & bağlam","Kullanıcı veya kurum sonucu tanımlar; kimlik, tenant ve güvenilir bağlam çalışma sınırını belirler."],["02","Policy & authorization","Hassas execution öncesi izinler, araç kapsamları, hedefler, bütçe ve onay gereksinimleri çözülür."],["03","Planla & orkestre et","Job sıralı ve sınırlandırılmış adımlara bölünür; deterministik servis veya akıllı yeteneklere yönlendirilir."],["04","Yürüt","Ajanlar/araçlar yalnız verilen scope içinde çalışır; istemciler backend otoritesinin projection'ıdır."],["05","Doğrula","Deterministik kontroller, güvenlik kapıları ve kabul kriterleri çıktının ilerleyip ilerleyemeyeceğini belirler."],["06","Kanıt & onay","Önemli olaylar, doğrulama sonuçları ve provenance korunur; policy gerekiyorsa bağımsız onay istenir."],["07","Teslim & izle","Kabul edilen sonuç teslim/deployment/yayın hazırlığına geçer ve durum/hata açısından izlenir."],["08","Kurtar & denetle","Retry edilebilir hatalar sınırlı recovery izler; diğerleri incelenebilir kayıtla durur veya escalation'a gider."]],
};

export default function ProductDeepDive({ locale, mode }: { locale: Locale; mode: Mode }) {
  const tr = locale === "tr";
  const base = tr ? "/tr" : "";
  if (mode === "capabilities") return <>
    <section className="shell page-hero"><div className="eyebrow">{tr ? "ILAIOS yetenekleri" : "ILAIOS capabilities"}</div><h1>{tr ? "Tek ürün. Birbirine bağlı üretim, zekâ, otomasyon ve güvenlik katmanları." : "One product. Connected layers for production, intelligence, automation and governance."}</h1><p className="lead">{tr ? "ILAIOS tek bir chatbot veya tek amaçlı üretim aracı değildir. Aynı kontrol modelinin altında şirket ve bireysel işlerini araştırma, yazılım, web, medya, otomasyon ve güvenlik akışlarına dönüştüren genişletilebilir bir platform olarak tasarlanır." : "ILAIOS is not a single chatbot or one-purpose generator. It is designed as an extensible platform that turns company and individual work into research, software, web, media, automation and security workflows under one control model."}</p></section>
    <section className="section"><div className="shell"><div className="section-heading"><div><div className="eyebrow">{tr ? "Yetenek haritası" : "Capability map"}</div><h2>{tr ? "Her modül farklı sorunu çözer; aynı yetki ve kanıt modeline bağlanır." : "Different modules solve different problems while sharing authority and evidence."}</h2></div><p className="muted">{tr ? "Bazı alanlar mevcut uygulanmış çekirdekler, bazıları ise kanonik ürün mimarisi ve geliştirme yönüdür. Site genel kullanıma açılmamış yetenekleri yayınlanmış hizmet gibi göstermez." : "Some areas are implemented foundations while others describe canonical product architecture and development direction. The site does not present unreleased capabilities as generally available services."}</p></div><div className="grid two-up">{capabilityCards[locale].map(c=><article className="card" key={c.title}><h3>{c.title}</h3><p>{c.text}</p><ul>{c.points.map(p=><li key={p}>{p}</li>)}</ul></article>)}</div></div></section>
    <section className="section"><div className="shell callout"><div><div className="eyebrow">{tr ? "Derine inin" : "Go deeper"}</div><h2>{tr ? "Yetenek listesinden çalışma sistemine geçin." : "Move from feature list to operating model."}</h2></div><div className="actions"><Link className="button" href={`${base}/core`}>{tr ? "Core'u incele" : "Explore Core"}</Link><Link className="button secondary" href={`${base}/enterprise`}>{tr ? "Kurumlar için" : "For enterprises"}</Link></div></div></section>
  </>;

  if (mode === "enterprise" || mode === "individuals") {
    const enterprise = mode === "enterprise";
    const cards: Card[] = tr ? (enterprise ? [
      {title:"Parçalı araç ve workflow'lar",text:"Farklı araçlar arasındaki manuel devri azaltmak için işleri job, policy, agent/tool ve evidence zincirinde birleştirir.",points:["Tekrarlanabilir süreç","Açık sorumluluk sınırı","İncelenebilir sonuç"]},
      {title:"Kontrolsüz AI kullanımı",text:"Model çıktısını otorite kabul etmek yerine izin, approval, deterministic validation ve evidence ile çevreler.",points:["Tool scope","Policy gate","Human approval"]},
      {title:"Yazılım, web ve medya üretim yükü",text:"Üretim işini ayrı factory workflow'larına dönüştürerek gereksinimden validasyona kadar standardize eder.",points:["Web Factory","App/Software Factory","Video/Media Factory"]},
      {title:"Denetlenebilirlik eksikliği",text:"Önemli job ve state değişimlerinde kim/ne/ne zaman bağlamının audit/evidence ile ilişkilendirilmesini hedefler.",points:["Provenance","Validation sonucu","Recovery geçmişi"]},
      {title:"Araştırma ve bilgi parçalanması",text:"Kaynak, iddia, risk ve proje ilişkilerini yapılandırılmış bilgi katmanına taşır.",points:["Research packet","Knowledge graph yönü","Kaynak izlenebilirliği"]},
      {title:"Hata sonrası belirsizlik",text:"Retry edilebilir ve edilemez hataları ayıran bounded recovery yaklaşımıyla sessiz başarısızlık yerine görünür state üretir.",points:["Failure classification","Bounded retry","Escalation/audit"]},
    ] : [
      {title:"Hedefi işe dönüştürme",text:"Bir fikri yalnız cevap olarak değil; araştırma, plan, üretim, kontrol ve teslim adımlarına dönüştüren workflow yaklaşımı sunar.",points:["Goal-to-workflow","Kontrollü araç kullanımı","Sonuç ve evidence"]},
      {title:"Kişisel otomasyon",text:"Tekrarlanan işleri schedule/state/recovery mantığıyla yönetilebilir hale getirmeyi hedefler.",points:["Recurring jobs","Progress visibility","Recovery"]},
      {title:"Web ve yazılım üretimi",text:"Site veya uygulama üretimini gereksinim, geliştirme ve kalite kapılarıyla yapılandırır.",points:["Web Factory","Software workflow","Validation"]},
      {title:"İçerik ve video üretimi",text:"Araştırmadan senaryo ve sahne planına, render ve yayın hazırlığına kadar uzun medya zincirini tek workflow'da toplar.",points:["Planning","Media/audio/render","Validation/publishing prep"]},
      {title:"Araştırma ve bilgi",text:"Kaynakları ve belirsizliği saklamadan araştırmayı yapılandırılmış çıktılara dönüştürür.",points:["Sources","Risk flags","Evidence"]},
      {title:"Desktop ve mobil deneyim",text:"İstemci tarafı sistem otoritesi olmak yerine backend durumunu güvenli biçimde gösteren bir kontrol yüzeyi olarak tasarlanır.",points:["Jobs/status","Approvals","Evidence visibility"]},
    ]) : (enterprise ? [
      {title:"Fragmented tools and workflows",text:"Connect work across tools as jobs governed by policy, agents/tools and evidence instead of manual hand-offs.",points:["Repeatable processes","Explicit responsibility boundaries","Reviewable outcomes"]},
      {title:"Uncontrolled AI use",text:"Surround model-assisted work with permissions, approval, deterministic validation and evidence instead of treating output as authority.",points:["Tool scopes","Policy gates","Human approval"]},
      {title:"Software, web and media delivery load",text:"Turn production work into factory workflows that standardize the path from requirements through validation.",points:["Web Factory","App/Software Factory","Video/Media Factory"]},
      {title:"Weak traceability",text:"Associate meaningful job and state changes with audit/evidence so teams can review who/what/when context.",points:["Provenance","Validation results","Recovery history"]},
      {title:"Fragmented research and knowledge",text:"Structure sources, claims, risks and project relationships into reusable knowledge workflows.",points:["Research packets","Knowledge graph direction","Source traceability"]},
      {title:"Unclear failure recovery",text:"Classify retryable and non-retryable failures and use bounded recovery instead of silent or infinite retries.",points:["Failure classification","Bounded retry","Escalation and audit"]},
    ] : [
      {title:"Turn a goal into work",text:"Treat an idea as a workflow with research, planning, production, validation and delivery—not only as a chat response.",points:["Goal-to-workflow","Controlled tool use","Outcome and evidence"]},
      {title:"Personal automation",text:"Make recurring work manageable through scheduling, state and recovery patterns.",points:["Recurring jobs","Progress visibility","Recovery"]},
      {title:"Build websites and software",text:"Structure site or application production around requirements, implementation and quality gates.",points:["Web Factory","Software workflow","Validation"]},
      {title:"Create content and video",text:"Connect research, script, scene planning, media/audio, render and publishing preparation into one workflow.",points:["Planning","Media/audio/render","Validation/publishing prep"]},
      {title:"Research and knowledge",text:"Turn research into structured outputs without hiding sources or uncertainty.",points:["Sources","Risk flags","Evidence"]},
      {title:"Desktop and mobile experience",text:"Clients are designed as secure projections of backend state rather than local sources of system authority.",points:["Jobs and status","Approvals","Evidence visibility"]},
    ]);
    return <>
      <section className="shell page-hero"><div className="eyebrow">{enterprise ? (tr?"Kurumlar için":"For enterprises") : (tr?"Bireysel kullanıcılar için":"For individuals")}</div><h1>{enterprise ? (tr?"AI'ı kurumsal işin içine kontrol, doğrulama ve izlenebilirlikle yerleştirin.":"Bring AI into operational work with control, validation and traceability.") : (tr?"Bir hedefi araştırmadan üretime ve doğrulanmış sonuca taşıyın.":"Move a goal from research to production and a verified outcome.")}</h1><p className="lead">{enterprise ? (tr?"ILAIOS; ekiplerin farklı operasyon, araştırma ve üretim işlerini tek bir model cevabına bırakmadan, açık yetki ve kanıt zinciriyle otomatikleştirmesi için tasarlanır.":"ILAIOS is designed so teams can automate operational, research and production work without handing authority to a single model response.") : (tr?"ILAIOS; araştırma, otomasyon, web/yazılım ve medya üretimini aynı kontrollü çalışma modeli altında birleştirmeyi hedefler.":"ILAIOS is designed to bring research, automation, web/software and media production under the same governed working model.")}</p></section>
      <section className="section"><div className="shell"><div className="section-heading"><div><div className="eyebrow">{tr?"Çözdüğü sorunlar":"Problems it addresses"}</div><h2>{tr?"Özellikten önce gerçek iş problemini görün.":"Start with the real work problem, not a feature list."}</h2></div><p className="muted">{tr?"Her alan gerçek kullanım sonucunu, kontrol mekanizmasını ve sınırlarını açıklar.":"Each area connects practical outcomes to controls and boundaries."}</p></div><div className="grid two-up">{cards.map(c=><article className="card" key={c.title}><h3>{c.title}</h3><p>{c.text}</p><ul>{c.points.map(p=><li key={p}>{p}</li>)}</ul></article>)}</div></div></section>
      <section className="section architecture-section"><div className="shell"><div className="eyebrow">{tr?"İş nasıl ilerler?":"How work moves"}</div><h2>{tr?"İstekten kabul edilmiş sonuca kadar görünür bir yaşam döngüsü.":"A visible lifecycle from request to accepted outcome."}</h2><div className="journey-grid">{operating[locale].map(([n,t,x])=><article className="journey-card" key={n}><span>{n}</span><h3>{t}</h3><p>{x}</p></article>)}</div></div></section>
    </>;
  }

  return <>
    <section className="shell page-hero"><div className="eyebrow">ILAIOS Core</div><h1>{tr?"Hatasızlık iddiası değil; hatayı sınırlayan, görünür kılan ve doğrulamaya zorlayan çekirdek.":"Not a claim of infallibility: a core designed to constrain, expose and validate failure."}</h1><p className="lead">{tr?"Hiçbir karmaşık yazılım sıfır hata garantisi veremez. ILAIOS Core'un amacı modelin veya aracın başarı iddiasına güvenmek yerine yetkiyi, context'i, validation'ı, evidence'ı ve recovery'yi sistemin ayrı kontrol noktaları haline getirmektir.":"No complex software can guarantee zero errors. ILAIOS Core is designed so authority, context, validation, evidence and recovery remain separate control points instead of trusting a model or tool to claim success."}</p></section>
    <section className="section"><div className="shell"><div className="core-diagram" role="img" aria-label={tr?"ILAIOS Core çalışma akışı":"ILAIOS Core operating flow"}>{operating[locale].map(([n,t,x])=><div className="core-node" key={n}><span>{n}</span><strong>{t}</strong><small>{x}</small></div>)}</div></div></section>
    <section className="section"><div className="shell"><div className="section-heading"><div><div className="eyebrow">{tr?"Doğrulanmış çekirdek temeller":"Verified core foundations"}</div><h2>{tr?"Kontrolü tek bir noktaya değil, birbirini tamamlayan mekanizmalara dağıtır.":"Control is distributed across complementary mechanisms rather than one claim of correctness."}</h2></div><p className="muted">{tr?"Repository durum kayıtlarında Bootstrap Validator, Immutable Context, Tool Gateway, Audit Engine, Validation Pipeline, Evidence Chain ve Confidence Scoring çekirdek modülleri tamamlanmış olarak kayıtlıdır.":"Repository status records identify Bootstrap Validator, Immutable Context, Tool Gateway, Audit Engine, Validation Pipeline, Evidence Chain and Confidence Scoring as completed core modules."}</p></div><div className="grid two-up">{capabilityCards[locale].slice(0,4).map(c=><article className="card" key={c.title}><h3>{c.title}</h3><p>{c.text}</p><ul>{c.points.map(p=><li key={p}>{p}</li>)}</ul></article>)}</div><div className="actions"><Link className="button" href={`${base}/capabilities`}>{tr?"Tüm yetenekler":"All capabilities"}</Link><Link className="button secondary" href={`${base}/architecture`}>{tr?"Mimari":"Architecture"}</Link></div></div></section>
  </>;
}
