import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata={title:"Mimari",description:"ILAIOS control-plane mimarisini, authority sınırlarını, shared knowledge plane'i, provider routing'i ve evidence yolunu inceleyin.",alternates:{canonical:"/tr/architecture",languages:{en:"/architecture",tr:"/tr/architecture","x-default":"/architecture"}}};
const layers=[["01","İstemciler","Web, Desktop, Mobile, API, CLI ve Enterprise Console platform state'inin controlled projection'larıdır; client request otorite değildir."],["02","Control plane","Backend otoritesi policy, tenant context, orchestration, durable state transition'ları ve kritik ürün kararlarını yönetir."],["03","Policy & approvals","Permissions, bütçe, risk koşulları ve gerekli human approval bounded execution öncesi çözülür."],["04","Capability fabric","Factory, agent, skill ve deterministik servisler açık contract ve scope alır."],["05","Routing & providers","Model, araç ve external provider'lar canonical routing ve policy arkasında seçilen değiştirilebilir kaynaklardır."],["06","Validation & evidence","Bağımsız kontroller, acceptance kriterleri, provenance ve evidence material result'ın ilerleyip ilerleyemeyeceğini belirler."],["07","Delivery & recovery","Kabul edilen outcome'lar delivery veya authorized side effect'e geçebilir; failure bounded repair, retry veya escalation izler."]] as const;
const boundaries=[["Authority","Request ≠ permission. Model anlatımı, agent identity veya tool access otoriteyi sessizce genişletemez."],["Context","Identity, tenant, project, classification ve purpose hangi context'in kullanılabileceğini belirler."],["Execution","Capability'ler admitted job için bounded work ve gereken minimum tool scope'u alır."],["Acceptance","Generated output gerekli validation ve evidence koşulları geçmeden final değildir."],["Recovery","Retry ve repair bounded'dır; çözülemeyen koşullar sonsuz döngü yerine durur veya escalation'a gider."]] as const;

export default function Page(){return <>
<section className="shell page-hero"><div className="eyebrow">Mimari</div><h1>Tek authoritative control plane. Birden çok governed capability.</h1><p className="lead">ILAIOS; kullanıcı arayüzlerini, intelligent capability'leri, provider kaynaklarını ve execution tools'u context, policy, state, validation, evidence ve recovery'yi yöneten backend otoritesinden ayırır.</p></section>
<section className="section architecture-section"><div className="shell"><div className="section-heading"><div><div className="eyebrow">Authority flow</div><h2>Intent aşağı ilerler; evidence ve accepted state geri döner.</h2></div><p className="muted">Mimari presentation, intelligence, execution ve permission'ın tek opak bileşende birleşmesini önler.</p></div><div className="control-stack">{layers.map(([n,t,x],i)=><div key={t}>{i>0&&<div className="stack-connector">controlled boundary ↓</div>}<div className={`stack-layer ${i===1?"authority-layer":""}`}><span>{n}</span><strong>{t}</strong><small>{x}</small></div></div>)}</div></div></section>
<section className="section"><div className="shell split-copy"><div><div className="eyebrow">Knowledge / RAG plane</div><h2>Knowledge execution'ı bilgilendirir; authority'ye dönüşmez.</h2></div><div><p className="lead small">Authorized context → project memory → source provenance → tenant-aware retrieval → grounded synthesis → evidence.</p><p className="muted">Knowledge/RAG cross-factory infrastructure'dır; finished-product factory değildir ve yalnız vector search olarak ele alınmaz.</p></div></div></section>
<section className="section evidence-section"><div className="shell"><div className="section-heading"><div><div className="eyebrow">Trust boundaries</div><h2>Capability, permission değildir.</h2></div><p className="muted">Her önemli sınır neyin, kimin adına, hangi context ile çalışabileceğini ve acceptance öncesi neyin kanıtlanması gerektiğini belirler.</p></div><div className="process-ledger">{boundaries.map(([t,x],i)=><article key={t}><span>{String(i+1).padStart(2,"0")}</span><div><h2>{t}</h2><p>{x}</p></div></article>)}</div></div></section>
<section className="section"><div className="shell split-copy"><div><div className="eyebrow">Provider bağımsızlığı</div><h2>Ürün beyni ILAIOS olarak kalır.</h2></div><div><p className="lead small">Model, external provider, editor ve tool'lar değişebilir; workflow authority'nin kaynağına veya user-facing product identity'ye dönüşemez.</p><p className="muted">Single routing truth, policy gate'leri ve capability contract'ları kaynaklar değişirken sistem sınırını korur.</p><div className="actions"><Link className="button" href="/tr/core">Core'u incele</Link><Link className="button secondary" href="/tr/platform/control-plane">Control plane</Link><Link className="text-link" href="/tr/docs">Dokümanlar →</Link></div></div></div></section>
</>}
