import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata={title:"Mimari",description:"ILAIOS control-plane mimarisini, yetki sınırlarını, yürütme modelini ve kanıt yolunu inceleyin.",alternates:{canonical:"/tr/architecture",languages:{en:"/architecture",tr:"/tr/architecture","x-default":"/architecture"}}};

const layers=[["01","İstemciler","Desktop, mobil ve web arayüzleri sistem durumunun kontrollü projeksiyonlarını sunar; hedefleri, onayları ve kullanıcı kararlarını toplar."],["02","Control plane","Backend otoritesi politika, yetkilendirme, tenant bağlamı, orkestrasyon, durum geçişleri ve kritik kararları yönetir."],["03","Politika ve onaylar","Hassas işler ilerlemeden önce izinler, onay gereksinimleri ve yürütme koşulları değerlendirilir."],["04","Yürütme ve araçlar","Deterministik adımlar tercih edilir; akıllı yetenekler sınırlandırılmış görev ve araç sözleşmeleri üzerinden çalışır."],["05","Doğrulama ve kanıt","Sonuçlar kontrol edilir; kalıcı kanıt kayıtları inceleme, denetim bağlamı, kurtarma ve hesap verebilir teslimi destekler."]] as const;
const boundaries=[["Yetki sınırı","Bir istemci veya ajan iş isteyebilir; ancak bir isteğin başarıyla üretilmiş olması onu otomatik olarak izne dönüştürmez."],["Yürütme sınırı","Araçlar ve servisler sınırsız ortam yetkisi devralmak yerine yalnızca onaylanmış iş için gerekli kapsamı alır."],["Doğrulama sınırı","Mümkün olduğunda tamamlanma; yalnızca model güvenine değil açık kontroller ve kabul kriterlerine göre belirlenir."],["Kanıt sınırı","Anlamlı yürütme olayları yeniden oluşturulabilir kalır; böylece operatörler ne olduğunu ve sonucun neden kabul edildiğini anlayabilir."]] as const;
const designQuestions=[["Otorite kimde?","Güvenlik ve ürün açısından kritik runtime kararlarının doğruluk kaynağı backend/control-plane servisleridir."],["Akıllı yetenekler nereye oturur?","Modeller ve ajanlar kontrollü iş akışları içindeki yeteneklerdir; planlama, yorumlama ve yürütmeye yardımcı olabilir ancak global otoriteyi sahiplenmez."],["Değişiklik nasıl sınırlandırılır?","Kalıcı sözleşmeler istemcileri, kontrol mantığını, yürütme servislerini ve kanıtı ayırır; bir arayüz değişirken sistem güven modeli yeniden tanımlanmaz."],["Hata nasıl davranır?","Kritik yollar; gerekli politika, onay, doğrulama veya kanıt koşulları sağlanmadığında duracak, eskale olacak veya beklemede kalacak şekilde tasarlanır."]] as const;

export default function Page(){return <>
  <section className="shell page-hero"><div className="eyebrow">Mimari</div><h1>Yetki control plane içinde kalır.</h1><p className="lead">ILAIOS; kullanıcı arayüzlerini, akıllı yetenekleri ve yürütme araçlarını politika, yetkilendirme, doğrulama, durum ve kanıtı yöneten backend otoritesinden ayırır.</p></section>
  <section className="section architecture-section"><div className="shell"><div className="section-heading"><div><div className="eyebrow">Sistem modeli</div><h2>Niyetten kanıta katmanlı yol.</h2></div><p className="muted">Her sınır; sunum, akıllı yetenek, yürütme ve otoritenin tek bir opak bileşende birleşmesini önlemek için vardır.</p></div><div className="control-stack">{layers.map(([n,t,x],i)=><div key={t}>{i>0&&<div className="stack-connector">kontrollü sınır ↓</div>}<div className={`stack-layer ${i===1?"authority-layer":""}`}><span>{n}</span><strong>{t}</strong><small>{x}</small></div></div>)}</div></div></section>
  <section className="section"><div className="shell"><div className="section-heading"><div><div className="eyebrow">Güven sınırları</div><h2>Yetki ile kapasiteyi ayırın.</h2></div><p className="muted">Plan üretebilmek, model çağırabilmek veya araca erişebilmek bir yan etki yaratma yetkisine sahip olmakla aynı şey değildir.</p></div><div className="grid two-up">{boundaries.map(([t,x])=><article className="card" key={t}><h3>{t}</h3><p>{x}</p></article>)}</div></div></section>
  <section className="section architecture-section"><div className="shell"><div className="eyebrow">Mimari soruları</div><h2>Dört soru işletim modelini tanımlar.</h2><div className="grid two-up">{designQuestions.map(([t,x])=><article className="card" key={t}><h3>{t}</h3><p>{x}</p></article>)}</div></div></section>
  <section className="section"><div className="shell split-copy"><div><div className="eyebrow">Temel kural</div><h2>İstemciler projeksiyondur, sistem otoritesi değildir.</h2></div><div><p className="lead small">Güvenlik ve ürün açısından kritik kararlar, yalnızca desktop veya mobil arayüz bunları gösterebildiği ya da isteyebildiği için istemciye devredilmez.</p><p className="muted">Bu ayrım, istemciler gelişirken politika, yürütme, doğrulama ve kanıt sözleşmelerinin backend tarafında kalıcı olmasını sağlar.</p><div className="actions"><Link className="button secondary" href="/tr/platform/control-plane">Control plane</Link><Link className="button secondary" href="/tr/security">Güvenlik modeli</Link><Link className="text-link" href="/tr/docs">Dokümanlar →</Link></div></div></div></section>
</>}
