import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata={title:"Güven Merkezi",description:"ILAIOS güvenlik mimarisi, erişim kontrolü, veri işleme ilkeleri, denetlenebilirlik, sorumlu yapay zekâ yaklaşımı ve kamusal iddia sınırlarını inceleyin.",alternates:{canonical:"/tr/trust",languages:{en:"/trust",tr:"/tr/trust","x-default":"/trust"}}};

const controls=[["Yetki açık kalır","Hassas işlemler model güvenine değil kimlik, izin ve gerekli onaylara dayanır."],["Kanıt incelenebilir kalır","Önemli yürütme ve doğrulama sonuçları yalnız başarı iddiasına indirgenmeden incelenebilir tutulmak üzere tasarlanır."],["Veri erişimi sınırlandırılır","Yetkili çalışma, sınırsız erişim yerine tenant farkındalığına sahip ve amaçla sınırlı bağlama dayanır."],["Modeller değiştirilebilir kalır","Model, sağlayıcı veya araç yürütmeye katkı verebilir; politika veya yetkilendirme kaynağına dönüşmez."]] as const;
const boundary=[["Bugün kamusal olarak","Mimari ilkeler, yetki sınırları, kanıt odaklı yürütme ve doğrulanmış kamusal iletişim kanalı."],["Yalnız doğrulamadan sonra","Bağımsız sertifikalar, denetim raporları, resmi uyumluluk statüsü, production taahhütleri ve müşteriye özel güvenceler."],["İma edilmez","Tasarlanmış bir kontrol harici denetim, sertifika, sözleşmesel garanti veya genel kullanıma açıklık kanıtı gibi sunulmaz."]] as const;

const sectionTitleStyle={fontSize:"clamp(1.9rem,3vw,3rem)",lineHeight:1.08,letterSpacing:"-0.035em",maxWidth:"20ch"} as const;
const boundaryCardStyle={background:"#141414",border:"1px solid #2A2A2A",boxShadow:"none"} as const;
const boundaryTitleStyle={color:"#FFFFFF",WebkitTextFillColor:"#FFFFFF"} as const;
const boundaryTextStyle={color:"#B3B3B3",WebkitTextFillColor:"#B3B3B3"} as const;

export default function Page(){return <>
  <section className="shell page-hero compact-page-hero"><div className="eyebrow">Güven Merkezi</div><h1>Güven rozetle değil, kanıtla başlar.</h1><p className="lead">ILAIOS sistemin uygulamak üzere tasarlandığı kontroller ile bağımsız olarak doğrulanmış durumu birbirinden ayırır. Kamusal iddialar bu sınırın içinde kalır.</p></section>
  <section className="section"><div className="shell"><div className="section-heading"><div><div className="eyebrow">Burada güven ne demek?</div><h2 style={sectionTitleStyle}>Hassas işlerin çevresinde kontrol, kanıt ve açık sınırlar.</h2></div><p className="muted">Güvenlik mimarisi kontrolleri açıklar. Bu sayfa ise bu kontrollerin kamusal olarak neyi kanıtladığını ve neyi kanıtlamadığını açıklar.</p></div><div className="principle-directory">{controls.map(([t,x],index)=><article key={t}><span>{String(index+1).padStart(2,"0")}</span><strong>{t}</strong><p>{x}</p></article>)}</div></div></section>
  <section className="section surface-section"><div className="shell"><div className="compact-heading-row"><div><div className="eyebrow">İddia sınırı</div><h2 style={sectionTitleStyle}>Bugün ne söylenebilir, ne daha güçlü kanıt gerektirir?</h2></div></div><div className="grid three-up">{boundary.map(([t,x])=><article className="card" style={boundaryCardStyle} key={t}><h3 style={boundaryTitleStyle}>{t}</h3><p style={boundaryTextStyle}>{x}</p></article>)}</div></div></section>
  <section className="section compact-section"><div className="shell callout"><div><div className="eyebrow">Kontrolleri mi arıyorsun?</div><h2 style={sectionTitleStyle}>Güvenlik modelini incele veya doğrulanmış kamusal kanalı kullan.</h2></div><div><p className="muted">Burada doğrulanmamış SOC 2, ISO 27001 veya eşdeğer sertifika iddiası yayınlanmaz. Güvenlik bildirimleri security@ilaios.com üzerinden iletilebilir.</p><div className="actions"><Link className="button" href="/tr/security">Güvenlik detayları</Link><a className="button secondary" href="mailto:security@ilaios.com">security@ilaios.com</a></div></div></div></section>
</>}
